default_stages: [commit, push]
fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: detect-private-key
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: requirements-txt-fixer
    -   id: detect-aws-credentials
-   repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
        exclude: (tests|script)
-   repo: https://github.com/ambv/black
    rev: 25.9.0
    hooks:
    -   id: black
        language_version: python3.13
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
    -   id: mypy
        exclude: ^doc/
-   repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.23.0
    hooks:
    -    id: commitlint
         stages: [commit-msg]
